name = "CityOfSquadron"
author = "Nodev_"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dd69479722549966dad8b6015eee913e9fdafe07236202d4efd4f5d781a5b7ba"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
