name = "CityOfSquadron"
author = "Nodev_"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e97ad93c4de94fa54c086107155e2067963b95cc87600aa83f018b914f6d463a"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"
