name = "CityOfSquadron"
author = "Nodev_"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "325f36116ae2b21e9a2da1f29fbd42ac11d714ca7f864f72b10a3e5a381812db"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"
